# Generated by Django 3.1.4 on 2021-01-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20201210_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='subforum',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='subforum_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.subforum'),
            preserve_default=False,
        ),
    ]
