# Generated by Django 3.1.4 on 2021-01-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210125_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
