# Generated by Django 3.1.4 on 2021-01-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20210125_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='icon',
            field=models.ImageField(default='default.jpg', upload_to='subforum_icons'),
        ),
    ]
