# Generated by Django 3.1.4 on 2021-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20210125_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='subforum_icons'),
        ),
    ]
