# Generated by Django 3.1.4 on 2021-02-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210203_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subforum',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='subforum_id',
            new_name='subforum',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='user_id',
            new_name='user',
        ),
    ]
