# Generated by Django 3.1.4 on 2021-02-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20210203_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='user',
            new_name='author',
        ),
    ]
